name: Daily Quote Update

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight UTC
  workflow_dispatch: # allows manual run button

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install firebase-admin node-fetch@2 typescript ts-node @types/node @types/node-fetch

      - name: Run script
        run: npx ts-node src/api/updateQuote.ts
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}